spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
# Mybatis配置
mybatis:
      mapperLocations: classpath*:mapper/**/*.xml
      configuration:
        map-underscore-to-camel-case: true
#shrio配置
shiro:
    enable: false
    expiretime : 3